### ISSUE TITLE
Innendrehen kaputt

### ISSUE THREAD

**Issue by mgmax** [fau-fablab/drehbank-fraese-autodesk#1]
laut @Virtex7 ist irgendwas beim Innendrehen kaputt.

**Comment by arwarw** [comment]
Also so generell hat das bei mir funktioniert. #2 ist zwar ein Problem, aber wenn man den Teiljob einzeln laufen laesst funktioniert er. Ein bischen spezifischere Fehlerbeschreibung waere toll ;)

**Comment by arwarw** [comment]
Inzwischen funktionieren auch Werkzeugwechsel mit Deckeloeffnen im selben Job. D.h. ich weiss nicht was da noch sein soll. Nachdem auch bisher niemand was spezifischeres dazu gesagt hat und diverse erfolgreiche Innendrehjobs passiert sind erklaere ich das mal fuer erledigt.
