### ISSUE TITLE
Werkzeugbibliothek unvollstaendig, bitte von WS11(?) kopieren

### ISSUE THREAD

**Issue by arwarw** [fau-fablab/drehbank-fraese-autodesk#4]
Ich habe vor ein paar Wochen die Innendrehwerkzeuge in Inventor erstellt, da sollte evtl jemand die Bibliotheken hier aktualisieren, oder falls das nicht so gedacht ist, die hiesigen wegwerfen, nicht dass jemand Werkzeuge vernichtet indem er den Kram hier drueberkopiert.

**Comment by mgmax** [comment]
Ich weiß nicht wie es gedacht ist, aber du hast auf jeden Fall 
Schreibzugriff auf das git repo.

**Comment by arwarw** [comment]
Behoben mit Commit 1765c12
